COMMENT =	Fetch and run Research Unix V4-V7 and 32V on SIMH
V =		0.1
DISTNAME =	prebsd-${V}
CATEGORIES =	emulators
MASTER_SITES =	https://github.com/moebiusV/prebsd/releases/download/v${V}/

MAINTAINER =	maintainer@example.com

PERMIT_PACKAGE =	Yes

NO_BUILD =	Yes
NO_TEST =	Yes
USE_GMAKE =	Yes
CONFIGURE_STYLE =	gnu

RUN_DEPENDS =	net/curl

.include <bsd.port.mk>
