; System III (PDP-11) disk boot — boot the installed miniroot.
set tto 7b
set cpu 11/70
set cpu 256K
set cpu idle
set rp0 rp06
att rp0 sysiii-rp06.disk
att tm0 sysiii-dist.tape
set console telnet=10026
boot rp0
