; V6 (pcollinson/unixv6-extras) — three RK05 disks on a PDP-11/40.
set cpu 11/40
set cpu idle
dep sr 177700
set tm0 writeenabled
attach tm0 tm0.tap
attach rk0 rk0
attach rk1 rk1
attach rk2 rk2
attach rk3 rk3
set console telnet=10023
boot rk0
